system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
data:
  input_folder: data/navi_v1
  output_folder: data/navi_feats
  model_name: videogpt
model:
  feat_dim: [128,128,128,128]
  feat_size: 128
batch_size: 1
optimizer:
  n_epochs: 10
  probe_lr: 0.00001
  model_lr: 0
defaults:
  - optimizer: ten_epoch
  - backbone: videogpt
  - dataset: navi_feats
  - probe: depth_dpt
  - _self_
